name: pricetracker
version: "0.2"
author: Jas B. <jas@bertovic.net>
about: LiveProject on Manning.com - simple tracker - Milestone 2.0
args:
    - from:
        short: f
        long: from
        required: true
        help: from date specified as yyyy-mm-dd
        takes_value: true
    - symbols:
        short: s
        long: sym
        help: symbols to fetch price data 
        required: true
        multiple: true
        use_delimiter: true
        takes_value: true
