name: pricetracker
version: "0.4"
author: Jas B. <jas@bertovic.net>
about: LiveProject on Manning.com - simple tracker - Milestone 4.0
args:
    - from:
        short: f
        long: from
        required: true
        help: from date specified as yyyy-mm-dd
        takes_value: true
    - symbols:
        short: s
        long: sym
        help: symbols to fetch price data 
        required: true
        multiple: true
        use_delimiter: true
        takes_value: true
    - csv:
        short: c
        long: csv
        help: name of file to output csv format
        required: false
        takes_value: true
    - server:
        short: x
        long: server
        help: starts server on localhost port 8080
        required: false
    - pool:
        short: p
        long: pool
        help: number of downloader actors
        takes_value: true
        default_value: "5"

