[package]
name = "pricefetchcli"
version = "0.4.0"
authors = ["Jas Bertovic <jas@bertovic.net>"]
edition = "2018"


[dependencies]
clap = {version = "2.3", features = ["yaml"]}
pricefetchlib = {path = "../pricefetchlib"}
anyhow = "1.0"

[[bin]]
name = "pricefetch"
path = "src/main.rs"