[package]
name = "pricefetchcli"
version = "0.2.0"
authors = ["Jas Bertovic <jas@bertovic.net>"]
edition = "2018"


[dependencies]
clap = {version = "2.3", features = ["yaml"]}
pricefetchlib = {path = "../pricefetchlib"}
